#!/bin/sh

### BEGIN INIT INFO
# Provides:          S99rclocal
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Extra start script
# Description:       Made some filesystem changes
### END INIT INFO

start() {
    chgrp shadow /etc/shadow
    chmod 640 /etc/shadow
}

stop() {
    echo "Nothing to stop."
}

restart() {
    echo "This step does nothing"
    exit 0
}

status() {
    echo "This step does nothing"
    exit 0
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac
